---
# file: roles/glance/tasks/main.yml

    - name: Install glance packages
      command: yum install -y openstack-glance python-glanceclient

    - name: set config options in glance-api.conf
      command: openstack-config --set /etc/glance/glance-api.conf database connection mysql://glance:{{ GLANCE_DBPASS }}@controller/glance

    - name: set config options in glance-registry.conf
      command: openstack-config --set /etc/glance/glance-registry.conf database connection mysql://glance:{{ GLANCE_DBPASS }}@controller/glance

    - name: create database
      command: mysql -e "CREATE DATABASE glance"
      run_once: true

    - name: grant 1
      command: mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '{{ GLANCE_DBPASS }}'"

    - name: grant 2
      command: mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '{{ GLANCE_DBPASS }}'"

    - name: flugh privs
      command: mysql -e "FLUSH PRIVILEGES"

    - name: work around for broken glance db sync
      script: roles/glance/files/glance_db_workaround.sh
      run_once: true

    - name: glance db sync
      command: su -s /bin/sh -c "glance-manage db_sync" glance

    - name: glance config and service set up
      script: roles/glance/files/glance.sh

    - name: glance image tests
      script: roles/glance/files/glance_tests.sh
