---
# file: roles/glance/tasks/main.yml

- name: Install glance packages
  command: yum install -y openstack-glance python-glanceclient

- name: set config options in glance-api.conf
  command: openstack-config --set /etc/glance/glance-api.conf database connection mysql://glance:{{ GLANCE_DBPASS }}@{{ CONTROLLER }}/glance

- name: set config options in glance-registry.conf
  command: openstack-config --set /etc/glance/glance-registry.conf database connection mysql://glance:{{ GLANCE_DBPASS }}@{{ CONTROLLER }}/glance

- name: create database
  command: mysql -e "CREATE DATABASE glance"
  ignore_errors: yes

- name: mysql grants
  shell: "{{ item }}"
  with_items:
   - mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '{{ GLANCE_DBPASS }}'"
   - mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '{{ GLANCE_DBPASS }}'"
   - mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'{{ CONTROLLER }}' IDENTIFIED BY '{{ GLANCE_DBPASS }}'"
   - mysql -e "FLUSH PRIVILEGES"

- name: check for glance_setup confirmation file
  command: cat ~/.has_glance_setup
  ignore_errors: yes
  register: glance_setup_check

- name: work around for broken glance db sync
  script: roles/glance/files/glance_db_workaround.sh
  when: glance_setup_check|failed

- name: glance db sync
  command: su -s /bin/sh -c "glance-manage db_sync" glance
  when: glance_setup_check|failed

- name: glance keystone user, service and endpoint setup and config
  shell: "{{ item }}"
  with_items:
   - keystone user-create --name=glance --pass={{ GLANCE_PASS }} --email={{ EMAIL }}
   - keystone user-role-add --user=glance --tenant=service --role=admin
   - openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_uri http://{{ CONTROLLER }}:5000
   - openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_host {{CONTROLLER }}
   - openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_port 35357
   - openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_protocol http
   - openstack-config --set /etc/glance/glance-api.conf keystone_authtoken admin_tenant_name service
   - openstack-config --set /etc/glance/glance-api.conf keystone_authtoken admin_user glance
   - openstack-config --set /etc/glance/glance-api.conf keystone_authtoken admin_password {{ GLANCE_PASS }}
   - openstack-config --set /etc/glance/glance-api.conf paste_deploy flavor keystone
   - openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_uri http://{{ CONTOLLER }}:5000
   - openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_host {{ CONTROLLER }}
   - openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_port 35357
   - openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_protocol http
   - openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken admin_tenant_name service
   - openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken admin_user glance
   - openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken admin_password {{ GLANCE_PASS }}
   - openstack-config --set /etc/glance/glance-registry.conf paste_deploy flavor keystone
   - keystone service-create --name=glance --type=image --description="OpenStack Image Service"
   - keystone endpoint-create --service-id=$(keystone service-list | awk '/ image / {print $2}') --publicurl=http://{{ CONTROLLER }}:9292 --internalurl=http://{{ CONTROLLER }}:9292 --adminurl=http://{{ CONTROLLER }}:9292
  when: glance_setup_check|failed
  register: glance_setup
  environment: ENVIRONMENT

- name: enable glance services
  service: name={{ item }} state=started enabled=yes
  with_items:
   - openstack-glance-api
   - openstack-glance-registry

- name: glance image tests
  script: roles/glance/files/glance_tests.sh
  when: glance_setup_check|failed

- name: set glance_setup confirmation file
  command: touch ~/.has_glance_setup
  when: glance_setup|success
