---
# file: roles/keystone/tasks/main.yml

- name: install Keystone
  yum: pkg={{item}} state=installed
  with_items:
   - openstack-keystone
   - python-keystoneclient

- name: Config database
  command: openstack-config --set /etc/keystone/keystone.conf database connection mysql://keystone:{{ KEYSTONE_DBPASS }}@{{ CONTROLLER }}/keystone

- name: Create MySQL database
  command: mysql -e "CREATE DATABASE keystone"
  ignore_errors: yes

- name: Grant 1
  command: mysql -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '{{ KEYSTONE_DBPASS }}'"

- name: Grant 2
  command: mysql -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '{{ KEYSTONE_DBPASS }}'"

- name: Grant 3
  command: mysql -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'{{ CONTROLLER }}' IDENTIFIED BY '{{ KEYSTONE_DBPASS }}'"

- name: Flush Privileges
  command: mysql -e "FLUSH PRIVILEGES"

- name: Define auth token
  command: openstack-config --set /etc/keystone/keystone.conf DEFAULT admin_token {{ ADMIN_TOKEN }}

- name: Step 6a
  command: keystone-manage pki_setup --keystone-user keystone --keystone-group keystone

- name: Step 6b
  command: chown -R keystone:keystone /etc/keystone/ssl

- name: Step 6c
  command: chmod -R o-rwx /etc/keystone/ssl

- name: Change ownership of /var/log/keystone
  command: chown -R keystone:keystone /var/log/keystone

- name: touch files
  command: touch /var/spool/cron/keystone /var/log/keystone/keystone-tokenflush.log

#- name: Step 8
#  command: (crontab -l -u keystone 2>&1 | grep -q token_flush) || echo '@hourly /usr/bin/keystone-manage token_flush >/var/log/keystone/keystone-tokenflush.log 2>&1' >> /var/spool/cron/keystone

- name: check for keystone_setup confirmation file
  command: cat ~/.has_keystone_setup
  ignore_errors: yes
  register: keystone_setup_check

- name: Keystone db sync
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone
  when: keystone_setup_check|failed

- name: enable Keystone service
  service: enabled=yes name=openstack-keystone state=started

- name: add keystone admin user
  shell: "{{ item }}"
  with_items:
   - keystone user-create --name=admin --pass={{ ADMIN_PASS }} --email={{ EMAIL }}
   - keystone role-create --name=admin
   - keystone tenant-create --name=admin --description="Admin Tenant"
   - keystone user-role-add --user=admin --tenant=admin --role=admin
   - keystone user-role-add --user=admin --role=_member_ --tenant=admin
  environment: SERVICE
  when: keystone_setup_check|failed

- name: add keystone demo user
  shell: "{{ item }}"
  with_items:
   - keystone user-create --name=demo --pass={{DEMO_PASS }} --email={{ EMAIL }}
   - keystone tenant-create --name=demo --description="Demo Tenant"
   - keystone user-role-add --user=demo --role=_member_ --tenant=demo
   - keystone tenant-create --name=service --description="Service Tenant"
  environment: SERVICE
  when: keystone_setup_check|failed

- name: create keystone service
  shell: keystone service-create --name=keystone --type=identity   --description="OpenStack Identity"
  environment: SERVICE
  when: keystone_setup_check|failed

- name: create keystone endpoint
  shell: keystone endpoint-create   --service-id=$(keystone service-list | awk '/ identity / {print $2}')   --publicurl=http://{{ CONTROLLER }}:5000/v2.0   --internalurl=http://{{ CONTROLLER }}:5000/v2.0   --adminurl=http://{{ CONTROLLER }}:35357/v2.0
  environment: SERVICE
  register: keystone_setup
  when: keystone_setup_check|failed

- name: set keystone_setup confirmation file
  command: touch ~/.has_keystone_setup
  when: keystone_setup|success
