---
# file: roles/nova/tasks/main.yml

- name: Install nova packages
  yum: pkg={{ item }} state=installed
  with_items:
   - openstack-nova-api
   - openstack-nova-cert
   - openstack-nova-conductor
   - openstack-nova-console
   - openstack-nova-novncproxy
   - openstack-nova-scheduler
   - python-novaclient

- name: set config options in nova.conf
  command: "{{ item }}"
  with_items:
   - openstack-config --set /etc/nova/nova.conf database connection mysql://nova:{{ NOVA_DBPASS }}@{{ CONTROLLER }}/nova
   - openstack-config --set /etc/nova/nova.conf DEFAULT rpc_backend qpid
   - openstack-config --set /etc/nova/nova.conf DEFAULT qpid_hostname {{ CONTROLLER }}
   - openstack-config --set /etc/nova/nova.conf DEFAULT my_ip {{ MY_IP }}
   - openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_listen {{ MY_IP }}
   - openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address {{ MY_IP }}

- name: create database
  command: mysql -e "CREATE DATABASE nova"
  ignore_errors: yes

- name: grant 1
  command: mysql -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY '{{ NOVA_DBPASS }}'"

- name: grant 2
  command: mysql -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY '{{ NOVA_DBPASS }}'"

- name: grant 3
  command: mysql -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'{{ CONTROLLER }}' IDENTIFIED BY '{{ NOVA_DBPASS }}'"

- name: flush privs
  command: mysql -e "FLUSH PRIVILEGES"

- name: check for nova_setup confirmation file
  command: cat ~/.has_nova_setup
  ignore_errors: yes
  register: nova_setup_check

- name: nova db sync
  command: su -s /bin/sh -c "nova-manage db sync" nova
  when: nova_setup_check|failed

- name: nova config, service and endpoint set up
  shell: "{{ item }}"
  with_items:
   - keystone user-create --name=nova --pass={{ NOVA_PASS }} --email={{ EMAIL }}
   - keystone user-role-add --user=nova --tenant=service --role=admin
   - openstack-config --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
   - openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_uri http://{{ CONTROLLER }}:5000
   - openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_host {{ CONTROLLER }}
   - openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_protocol http
   - openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_port 35357
   - openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_user nova
   - openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_tenant_name service
   - openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_password {{ NOVA_PASS }}
   - keystone service-create --name=nova --type=compute --description="OpenStack Compute";
   - keystone endpoint-create --service-id=$(keystone service-list | awk '/ compute / {print $2}') --publicurl=http://{{ CONTROLLER }}:8774/v2/%\(tenant_id\)s --internalurl=http://{{ CONTROLLER }}:8774/v2/%\(tenant_id\)s --adminurl=http://{{ CONTROLLER }}:8774/v2/%\(tenant_id\)s
  register: nova_setup
  when: nova_setup_check|failed
  environment: ENVIRONMENT

- name: enable nova services
  service: enabled=yes name={{ item }} state=started
  with_items:
   - openstack-nova-api
   - openstack-nova-cert
   - openstack-nova-consoleauth
   - openstack-nova-scheduler
   - openstack-nova-conductor
   - openstack-nova-novncproxy

- name: set has_nova_setup confirmation file
  command: touch ~/.has_nova_setup
  when: nova_setup|success
